theme: jekyll-theme-hacker

title: Paid High Tech Apprenticeship Program
author: ApprenTech

#avatar: "/assets/img/avatar-icon.png"
#round-avatar: true

# If you want to have an image logo in the top-left corner instead of having the title of the website,
# then specify the following parameter
#title-img: /path/to/image


#####################################
# --- Footer social media links --- #
#####################################

# Select the social network links that you want to show in the footer.
# Uncomment the links you want to show and add your information to each one.
social-network-links:
  email: "hello@apprentech.io"
  rss: true  # remove this line if you don't want to show an RSS link at the bottom
  facebook: apprentech
  github: apprentech


# Select which social network share links to show in posts
share-links-active:
  twitter: true
  facebook: true
  linkedin: true

# How to display the link to your website in the footer
# Remove this if you don't want a link in the footer
url-pretty: "apprentech.io"


# The keywords to associate with your website, for SEO purposes
#keywords: "my,list,of,keywords"

# Alternatively, the navbar, footer, and page background can be set to an image
# instead of colour

#navbar-img: "/assets/img/bgimage.png"
#footer-img: "/assets/img/bgimage.png"
#page-img: "/assets/img/bgimage.png"

#################################
# --- Web Analytics Section --- #
#################################

# Fill in your Google Analytics gtag.js ID to track your website using gtag
gtag: "G-G29QCX5NTK"

# Fill in your Google Analytics ID to track your website using Google Analytics
google_analytics: "G-G29QCX5NTK"


################
# --- Misc --- #
################

# Ruby Date Format to show dates of posts
date_format: "%B %-d, %Y"

# Facebook App ID
#fb_app_id: ""
